name: Create release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to create'
        required: true

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Check version in tpay.php
        run: if [ $(grep ${{ github.event.inputs.version }} tpay.php -c) != 2 ]; then exit 1; fi

      - name: Check Changelog
        run: if [ $(grep ${{ github.event.inputs.version }} CHANGELOG.md -c) != 1 ]; then exit 1; fi

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.1
          extensions: none, curl, dom, mbstring, simplexml, tokenizer, xml, xmlwriter, json
          coverage: none

      - run: composer install --no-dev

      - run: chmod 777 -R vendor

      - run: git archive --output=tpay-woocommerce.zip HEAD

      - run: zip -ur tpay-woocommerce.zip vendor/

      - name: Create Github release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.version }}
          name: "v${{ github.event.inputs.version }}"
          generateReleaseNotes: true
          artifacts: tpay-woocommerce.zip

