name: Pull request

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  phive:
    name: Install tools
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install tools
        uses: ngmy/phive-install-action@master
      - name: Upload tools to artifact store
        uses: actions/upload-artifact@master
        with:
          name: tools
          path: .dev-tools/tools

  check:
    needs: phive
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.1
          extensions: none, curl, dom, mbstring, simplexml, tokenizer, xml, xmlwriter, json
          coverage: none

      - run: composer install --no-dev

      - run: chmod 777 -R vendor

      - name: Download tools from artifact store
        uses: actions/download-artifact@master
        with:
          name: tools
          path: .dev-tools/tools
      - name: Set tools as an executable
        run: find .dev-tools/tools -type f -print0 | xargs -0 chmod +x

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: none, curl, dom, mbstring, simplexml, tokenizer, xml, xmlwriter, json
          coverage: none

      - run: cd .dev-tools && tools/php-scoper add-prefix -fq --config=./scoper.inc.php

      - run: git archive --output=tpay-woocommerce.zip HEAD

      - run: rm -rf vendor/paragonie
      - run: rm -rf vendor/phpseclib
      - run: rm -rf vendor/psr

      - run: composer dump-autoload

      - run: zip -ur tpay-woocommerce.zip vendor/

      - run: zip -ur tpay-woocommerce.zip vendor_prefixed/

      - run: mkdir plugin && unzip tpay-woocommerce.zip -d plugin

      - uses: actions/upload-artifact@v4
        id: plugin-upload
        with:
          name: 'tpay-woocommerce'
          path: 'plugin/'

      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            Tpay Woocommerce plugin - ${{ steps.plugin-upload.outputs.artifact-url }}
