name: Pull request

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.1
          extensions: none, curl, dom, mbstring, simplexml, tokenizer, xml, xmlwriter, json
          coverage: none

      - run: composer install --no-dev

      - run: chmod 777 -R vendor

      - run: git archive --output=tpay-woocommerce.zip HEAD

      - run: zip -ur tpay-woocommerce.zip vendor/

      - run: mkdir plugin && unzip tpay-woocommerce.zip -d plugin

      - uses: actions/upload-artifact@v4
        id: plugin-upload
        with:
          name: 'tpay-woocommerce'
          path: 'plugin/'

      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            Tpay Woocommerce plugin - ${{ steps.plugin-upload.outputs.artifact-url }}
